### ISSUE TITLE
Coordinate uncertainty

### ISSUE THREAD

**Issue by hsplendens** [DataDrivenEcologicalSynthesis/CitizenScienceOnLockdown#12]
I am testing out the issue feature. Is this how it works? 

After today's meeting, I went into the Large GBIF dataset that we downloaded using Shuang's awesome key. There is a variable named: coordinateUncertaintyInMeters. From what I see, it has quite a wide range (NA, and from 1 to 4226661 [the Earth basically]). I went and checked the one observation that had that huge variability (here: https://www.inaturalist.org/observations/12281213) and it does show a huge area of uncertainty. 

I think that we should add in a filter to keep only observations that have a reasonable accuracy given that we are selecting them based on their presence inside the city polygons. 

- What do you want to pick as a reasonable precision? 
- Should we exclude all the ones that have NAs for that variable? From what I can gather, most of the data has a pretty good accuracy (<200 m).

**Comment by shuanggeek** [comment]
After the discussion, we decided that <1km could be a good balance between getting enough data and the accuracy of the georeference to be located within a city boundary
